use db_mmorpg;

CREATE TABLE REGISTROS_USUARIOS (
id_registro INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
movimiento VARCHAR(70),
fecha_movimiento DATETIME NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE SANCIONES (
id_sancion INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
movimiento VARCHAR(200),
fecha_movimiento DATETIME NULL DEFAULT CURRENT_TIMESTAMP
);



